heat_template_version: 2017-02-24

description: >
  A stack containing an Autoscaling Group whose members automatically heal
  themselves if they are stopped, deleted, or go into an error state, using an
  Aodh alarm delivered to a Zaqar queue that triggers a Mistral workflow to
  replace the stopped server. Note that this requires event alarms to be
  enabled in Aodh, following the instructions at
  https://docs.openstack.org/aodh/latest/contributor/event-alarm.html#configuration
  (specifically by adding the publisher "notifier://?topic=alarm.all" in
  /etc/ceilometer/event_pipeline.yaml).

parameters:
  flavor:
    type: string
    description: Flavor for the instances to be created
    default: 07905559-28c3-41f2-b6a8-90ec6c21bd25
    constraints:
      - custom_constraint: nova.flavor
        description: Must be a flavor known to Nova
  image:
    type: string
    description: >
      Name or ID of the image to use for the instances.
    default: 1525aeac-1a8e-4696-b715-f8f9ffa8f0b9
    constraints:
      - custom_constraint: glance.image
        description: Must identify an image known to Glance
  network:
    type: string
    description: The network for the VM
    default: d5b4b0d4-5d1d-4407-b37e-378962e53c5f
  port:
    type: number
    description: The port to reply to requests on
    default: 8080

resources:
  servers:
    type: OS::Heat::AutoScalingGroup
    properties:
      resource:
        type: https://raw.githubusercontent.com/herr-hxp/heat-ah-testing/main/autohealing_server.yaml
        properties:
          flavor: {get_param: flavor}
          image: {get_param: image}
          network: {get_param: network}
          port: {get_param: port}
          root_stack_id: {get_param: "OS::stack_id"}
      min_size: 1
      desired_capacity: 2
      max_size: 4

outputs:
  server_ids:
    description: A list of the current server UUIDs
    value: {get_attr: [servers, refs]}
  ip_addresses:
    description: A list of server IP addresses
    value: {get_attr: [servers, outputs_list, first_address]}
